# Site settings
title: Yoga With Alison
email: yogawithalison1@gmail.com

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C39BD3 #80B3FF
  primary-rgb: "195, 155, 211" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Alison
  social: Contact Me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:yogawithalison1@gmail.com
  - title: facebook
    url: https://www.facebook.com/YogawithAlison1
  - title: github
    url: http://github.com/yogawithalison

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

collections:
  testimonials:
    output: true
  timetable:
    output: true
  gallery:
    output: true
